// recite-sync — a tiny Cloudflare Worker that stores one JSON blob per sync code
// in your own KV namespace. Deploy it with the "Deploy to Cloudflare" button in
// the repo README (or copy-paste from the Cloudflare dashboard), then fill the
// Worker URL + a sync code in 设置 → 云同步.
//
// API (all cross-origin, all JSON):
//   GET  /:key            → 200 {v, date, data}   (200 {v:1, data:null} if the key is unused)
//   PUT  /:key  body:data → 200 {ok:true}
//   OPTIONS *             → CORS preflight
//
// Auth: the sync code IS the credential (it is the KV key and unguessable).
// Optionally set a TOKEN secret (`wrangler secret put TOKEN` or the dashboard's
// Settings → Variables) to additionally require an `Authorization: Bearer TOKEN`
// header — useful when several people share one deployment.
//
// No rate limiting beyond the sync code's unguessability: each deployment runs
// on the owner's own free-tier quota (100k reads / 1k writes per day).

// Type-only stand-in for wrangler's generated `KVNamespace` (created on deploy
// as worker-configuration.d.ts); avoids a devDependency on @cloudflare/workers-types.
interface KVNamespace {
  get(key: string): Promise<string | null>;
  put(key: string, value: string): Promise<void>;
}

const JSON_HEADERS = {
  'content-type': 'application/json',
  'access-control-allow-origin': '*',
  'access-control-allow-methods': 'GET, PUT, OPTIONS',
  'access-control-allow-headers': 'content-type, authorization',
  'access-control-max-age': '86400',
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: JSON_HEADERS });
}

export default {
  async fetch(request: Request, env: { KV?: KVNamespace; TOKEN?: string }): Promise<Response> {
    if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: JSON_HEADERS });
    if (!env.KV) return json({ error: 'KV binding missing — re-run the deploy setup' }, 500);

    // Optional shared-secret layer (enable by setting the TOKEN secret).
    if (env.TOKEN && request.headers.get('authorization') !== `Bearer ${env.TOKEN}`) return json({ error: 'unauthorized' }, 401);

    const key = new URL(request.url).pathname.slice(1);
    // Sanity-check the key so arbitrary paths can't be probed: sync codes are
    // generated by the app (16 chars of [a-z0-9]), but users may set their own.
    if (!/^[A-Za-z0-9_-]{4,128}$/.test(key)) return json({ error: 'bad key' }, 400);

    if (request.method === 'GET') {
      const raw = await env.KV.get(key);
      if (raw == null) return json({ v: 1, data: null });
      return new Response(raw, { status: 200, headers: JSON_HEADERS });
    }
    if (request.method === 'PUT') {
      const body = await request.text();
      if (!body || body.length > 25 * 1024 * 1024) return json({ error: 'bad body' }, 400); // KV value cap is 25 MB
      await env.KV.put(key, body);
      return json({ ok: true });
    }
    return json({ error: 'method not allowed' }, 405);
  },
};
